### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.5/bin/./Data/pokemon.txt'

### ISSUE THREAD

**Issue by mattMillerC** [LazoCoder/Pokemon-Terminal#4]
I'm getting a `FileNotFoundError`. Running on Python 3.5.

```
Traceback (most recent call last):
  File "/Users/35131/Projects/Pokemon-Terminal-master/pokemon", line 201, in <module>
    single_argument_handler(argv[1].lower())
  File "/Users/35131/Projects/Pokemon-Terminal-master/pokemon", line 143, in single_argument_handler
    db = Database()
  File "/Users/35131/Projects/Pokemon-Terminal-master/database.py", line 53, in __init__
    self.__load_data()
  File "/Users/35131/Projects/Pokemon-Terminal-master/database.py", line 174, in __load_data
    data_file = open(path, "r+")
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.5/bin/./Data/pokemon.txt'
```

**Comment by LazoCoder** [comment]
Fixed. Let me know if it works for you now. 
Also thanks for bringing up this issue!

**Comment by restlessCalm** [comment]
Still getting this error even after the fix.

**Comment by DrMartinLutherXing** [comment]
Still appears to be a not found.

I adjusted your Database __init__
to set self.directory = os.path.dirname(os.path.realpath(__file__))
and reverted the changes from your last commit

I also had to modify the scripter.py file defining at the top
cwd = os.path.dirname(os.path.realpath(__file__))
and replaced occurrences of os.get_exec_path()[0] with the cwd value.

os.get_exec_path returns the path to the interpreter I think.

**Comment by DrMartinLutherXing** [comment]
Working for you now @restlessCalm ?

**Comment by AnirudhMurali** [comment]
Getting the same error.

```
Anirudhs-MacBook-Pro:~ Anirudh$ pokemon help
Traceback (most recent call last):
  File "/Users/Anirudh/Pokemon/pokemon", line 201, in <module>
    single_argument_handler(argv[1].lower())
  File "/Users/Anirudh/Pokemon/pokemon", line 143, in single_argument_handler
    db = Database()
  File "/Users/Anirudh/Pokemon/database.py", line 53, in __init__
    self.__load_data()
  File "/Users/Anirudh/Pokemon/database.py", line 174, in __load_data
    data_file = open(os.get_exec_path()[0] + path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.6/bin/./Data/pokemon.txt'
```

**Comment by DrMartinLutherXing** [comment]
Try the changes I listed above @AnirudhMurali

**Comment by LazoCoder** [comment]
I've changed the code as per @DrMartinLutherXing's suggestion. Hopefully this has resolved the issue. Let me know if its fixed!

Also, thanks so much @DrMartinLutherXing for the help. I've added you to the credits at the bottom of the readme.

**Comment by AnirudhMurali** [comment]
Thank you, works now! 😄
![image](https://user-images.githubusercontent.com/3096325/26852171-0349270a-4b2b-11e7-819a-9034704d9fa6.png)

**Comment by LazoCoder** [comment]
Hell yeah!
